from collective.z3cform.jqueryui.autocomplete.interfaces import IAutocompleteWidget
from collective.z3cform.jqueryui.datepicker.interfaces import IDatePickerWidget, IDateTimePickerWidget
from collective.z3cform.jqueryui.slider.interfaces import ISliderWidget